name: learn-env
channels:
  - defaults
  - plotly
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.5
  - pip:
      - pandas
      - numpy
      - matplotlib
      - pillow
      - streamlit
      - scikit-surprise
